[variables]
PLAYWRIGHT_BROWSERS_PATH = "/app/pw-browsers"

[phases.setup]
nixPkgs = ["python3", "chromium"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "PLAYWRIGHT_BROWSERS_PATH=/app/pw-browsers python bot.py"